depth:=../..
subdirs:=
uses:=
lib:=ip
LIBOBJS:=ip.o ip-filter.o ipIterator.o \
iface.o iface-native.o iface-registry.o \
udp.o packet-queue.o icmp.o util.o

include $(depth)/make.mk

.PHONY:: all clean depend libs libip tst
