#!/bin/bash

mount /mnt/packos
cp sample-simple  /mnt/packos/kernel
umount /mnt/packos

qemu -d int -net nic,model=rtl8139 -net user -fda ../../kernel/floppy.img -hda ../../kernel/hd-grub.img -boot c

