#!/bin/bash

mount /mnt/packos
cp sample-pci  /mnt/packos/kernel
sleep 1
umount /mnt/packos

qemu-system-i386 -s -d int -net nic,macaddr=00:e0:b8:ac:3d:25,model=rtl8139 -net tap,ifname=tap0 -fda ../../kernel/floppy.img -hda ../../kernel/hd-grub.img -boot c
