#!/bin/bash

mount /mnt/packos
cp sample-pci  /mnt/packos/kernel
umount /mnt/packos

#QEMU=~francis/incoming/os/qemu/qemu-0.8.2/i386-softmmu/qemu
QEMU=qemu

$QEMU -s -d int -net nic,macaddr=00:e0:b8:ac:3d:25,model=rtl8139 -net tap -fda ../../kernel/floppy.img -hda ../../kernel/hd-grub.img -boot c
